title: setsevireon
baseURL: https://setsevireon.github.io/
languageCode: en-us
theme: github.com/setsevireon/photophobia

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 10

languages:
  en:
    weight: 1
    contentDir: content/en
  pt:
    weight: 2
    contentDir: content/pt

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: null
  site_logo: null
  description: When I blog, I blog here.
  recent_posts_number: 10

markup:
  highlight:
    style: native
